# Generated by Django 5.2.6 on 2025-09-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Dejar en blanco para autogenerar.', max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Se recomienda una imagen de proporción cuadrada (ej. 400x400px) para una mejor visualización.', null=True, upload_to='categories/', verbose_name='Imagen Representativa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Breve')),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para buscadores (Google). Máximo 165 caracteres.', max_length=165, verbose_name='Meta Descripción (para SEO)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(blank=True, help_text='Dejar en blanco para autogenerar.', max_length=220, unique=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código del Producto (SKU)')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Especificaciones')),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para buscadores (Google). Máximo 165 caracteres.', max_length=165, verbose_name='Meta Descripción (para SEO)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre del Color')),
                ('color_hex', models.CharField(blank=True, help_text='Ej: #FF5733', max_length=7, verbose_name='Código Hex del Color')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Talla / Capacidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Real')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Oferta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'unique_together': {('product', 'color_name', 'size')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Se recomienda una imagen cuadrada (ej. 500x500px) para una mejor visualización en las tarjetas.', upload_to='products/', verbose_name='Imagen')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='Variante del Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
            },
        ),
    ]
