# Generated by Django 5.2.6 on 2025-09-21 13:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Se recomienda una imagen de proporción cuadrada (ej. 400x400px) para una mejor visualización.', max_length=255, null=True, verbose_name='Imagen Representativa'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Se recomienda una imagen cuadrada (ej. 500x500px) para una mejor visualización en las tarjetas.', max_length=255, verbose_name='Imagen'),
        ),
    ]
